name: "Perform Benchmarks"
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 */1 * * *"
jobs:
  perform_benchmarks:
    name: "Benchmarks"
    runs-on: windows-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install pillow git+https://github.com/justfoolingaround/animdl.git pkginfo

      - name: Run generator.py
        run: |
            python "generator.py"
        env:
          JUSTANOTHERWAIFU: ${{ secrets.JUSTANOTHERWAIFU }}
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: Benchmark Update"
          file_pattern: "api/*"
          repository: .
          skip_fetch: false
